# -*- coding: utf-8 -*-
"""Foundly - Matching System (Prototype-v0.01)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XcKF8NM4UZhL_axhD0sdkuWDa0cJPgLQ
"""

import requests
from PIL import Image # -> Pillow for image manipulation
from io import BytesIO # -> jalur? transit fot get the binnary file data
import matplotlib.pyplot as plt

# future machine learning engine (maybe)
import torch
import torchvision.models as models
import torchvision.transforms as transforms

# END OF SETUP THE LIBRARY

def load_image_from_url(url):
  try:
    response = requests.get(url, timeout=10)
    response.raise_for_status()

    img = Image.open(BytesIO(response.content)).convert('RGB')
    return img

  except Exception as e:
    print(f"Error: {e}")
    return None

# END OF IMPORT IMAGE

# TEMP Data with the correct flow
# TEMP_URL_LOST_ITEM = "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=600&auto=format&fit=crop"
# TEMP_URL_FOUND_ITEM = "https://images.unsplash.com/photo-1605464315542-bda3e2f4e605?q=80&w=600&auto=format&fit=crop"

# TEMP Data with the maintain flow
TEMP_URL_LOST_ITEM = "https://images.unsplash.com/photo-1587313170527-446f86d0c3d9?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
TEMP_URL_FOUND_ITEM = "https://images.unsplash.com/photo-1587333980975-8cba59fb15d0?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"

img_lost_item = load_image_from_url(TEMP_URL_LOST_ITEM)
img_found_item = load_image_from_url(TEMP_URL_FOUND_ITEM)

# visualization if the the data inputed to the RAM (computer)
if img_lost_item and img_found_item:
  fig, axes = plt.subplots(1, 2, figsize=(10, 5))

  axes[0].imshow(img_lost_item)
  axes[0].set_title("Lost Item from repoter")
  axes[0].axis('off')

  axes[1].imshow(img_found_item)
  axes[1].set_title("Found Item from founder")
  axes[1].axis('off')

  plt.show()

RESIZED_VALUE = 224
MEAN_VALUE = [0.485, 0.456, 0.406]
STD_VALUE = [0.229, 0.224, 0.225]

# define the transformation
transformation_img = transforms.Compose([
    transforms.Resize((RESIZED_VALUE, RESIZED_VALUE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=MEAN_VALUE, std=STD_VALUE)
])

tensor_lost_item = transformation_img(img_lost_item).unsqueeze(0)
tensor_found_item = transformation_img(img_found_item).unsqueeze(0)

# END OF TRANSFORMATION IMAGE

# use ResNet50 in my device
# tested in: RTX 5060ti 16gb
import torch.nn as nn

model_resnet = models.resnet50(pretrained=True)

model_resnet.fc = nn.Identity()
model_resnet.eval()

# END OF LOAD RESNET50

import torch.nn.functional as F

MINIMUM_SCORE = 85.0

with torch.no_grad():
  # DNA ekstraction or feature embedding
  feature_lost_item = model_resnet(tensor_lost_item)
  feature_found_item = model_resnet(tensor_found_item)

  # count Cosine Similarity
  similarity_score = F.cosine_similarity(feature_lost_item, feature_found_item)
  score_persentage = (similarity_score.item() + 1) / 2 * 100
  print(f"SIMILARITY SCORE: {score_persentage}")

  print("RESULT FOR THE IMAGE SIMILARITY")
  if score_persentage >= MINIMUM_SCORE:
    print("STATUS: Item is found")
  else:
    print("STATUS: the item is not suitable")

# install Sentence Transformers
# ATTENTION NOTES: run just one time
!pip install sentence-transformers

# load the NLP model
# use 'all-MiniLM-L6-v2
from sentence_transformers import SentenceTransformer, util

model_nlp = SentenceTransformer("all-MiniLM-L6-v2")

# Simulation payload text from nodejs (asumtion)
TEMP_TEXT_LOST_ITEM = "Nama: Earphone Wireless. Kategori: Elektronik. Lokasi: Sekitaran kantin kampus. Deskripsi: Earphone lenovo warna hitam."
TEMP_TEXT_FOUND_ITEM = "Nama: Earphone Wireless. Kategori: Elektronik. Lokasi: Meja di Lorong Laboratorium. Deskripsi: Earphone wireless Lenovo warna hitam ditemukan pada meja Laboratorium."

vector_lost_item = model_nlp.encode(TEMP_TEXT_LOST_ITEM, convert_to_tensor=True)
vector_found_item = model_nlp.encode(TEMP_TEXT_FOUND_ITEM, convert_to_tensor=True)

text_score = util.cos_sim(vector_lost_item, vector_found_item)
text_persentage_score = text_score.item() * 100

print(f"TEXT SCORE: {text_persentage_score:.2f}%")

import json

IMG_WEIGHT = 0.60
TEXT_WEIGHT = 0.40

img_score = score_persentage
text_score = text_persentage_score

final_score = (img_score * IMG_WEIGHT) + (text_score * TEXT_WEIGHT)

# Rule Based Filtering (asumtion payload from node js response)
TEMP_LOST_ITEM_CATEGORY = "Elektronik"
TEMP_FOUND_ITEM_CATEGORY = "Elektronik"

# Var initialization
match_status = False
reason_msg = ""

if TEMP_LOST_ITEM_CATEGORY.lower() != TEMP_FOUND_ITEM_CATEGORY.lower():
  final_score = 0.0
  reason_msg = "GAGAL: Kategori barang berbeda"
elif final_score >= MINIMUM_SCORE:
  match_status = True
  reason_msg = "SUKSES: Skor memenuhi standar akurasi Foundly."
else:
  match_status = False
  reason_msg = f"GAGAL: Skor akhir ({final_score:.2f}%) di bawah batas minimal ({MINIMUM_SCORE}%)."

# Format output
output_response = {
    "matching_id": 102,
    "lost_item_id": 45,
    "found_item_id": 46,
    "score_detail": {
        "visual_persentage": round(img_score, 2),
        "text_persentage": round(text_score, 2),
    },
    "final_score_persentage": round(final_score, 2),
    "is_match": match_status,
    "notes": reason_msg
}

print(f"FINAL RESPONSE")
print(json.dumps(output_response, indent=4))

